# frozen_string_literal: true

RSpec.describe 'route tabs' do
  # Renders the groups on their own, so assertions see exactly the markup the
  # adapter emits for them -- no page shell to slice it back out of.
  def render_components(adapter, apps)
    components = apps.map { |app| app.components.last }
    state = apps.map(&:state).inject({}, :merge)

    Class.new(Phlex::HTML) do
      define_method(:adapter) { adapter }
      define_method(:view_template) { components.each { |component| component.render(self, state) } }
    end.new.call
  end

  def render_group(adapter, app)
    render_components(adapter, [app])
  end

  def tabs_app(url: false, key: :view, lazy: false, active: 0, labels: %w[Alpha Beta])
    StreamWeaver::App.new('route tabs spec') do
      tabs(key, url: url, lazy: lazy) do
        labels.each { |label| tab(label) { text label } }
      end
    end.tap { |app| app.rebuild_with_state({ key => active }) }
  end

  describe 'in http mode' do
    let(:adapter) { StreamWeaver::Adapter::AlpineJS.new }
    let(:html) { render_group(adapter, tabs_app(url: true)) }

    it 'switches the tab with Alpine and pushes the new index to the URL' do
      expect(html).to include(%q{:class="{ 'sw-tab-active': activeTab === 1 }"})
      expect(html).to include(%q{@click="activeTab = 1; swRouteTabs.push('view', 1)"})
    end

    it 'makes no HTMX request when a tab is clicked' do
      expect(html).not_to include('hx-post')
      expect(html).not_to include('hx-vals')
      expect(html).not_to include('hx-swap')
    end

    it 'emits no hidden state-sync input for the group' do
      expect(html).not_to include('type="hidden"')
    end

    it 'derives the active tab from the URL rather than from server state' do
      stale = render_group(adapter, tabs_app(url: true, active: 1))

      expect(stale).to include(%q{x-data="{ activeTab: swRouteTabs.read('view', 2) }"})
      expect(stale).not_to include('activeTab: 1 }')
    end

    it 're-derives the active tab when the browser moves through history' do
      expect(html).to include(%q{@popstate.window="activeTab = swRouteTabs.read('view', 2)"})
    end

    it 'ships the URL helper with the group' do
      expect(html).to include('window.swRouteTabs')
    end

    it 'ships the URL helper once however many groups a page has' do
      groups = [tabs_app(url: true), tabs_app(url: true, key: :panel)]

      expect(render_components(adapter, groups).scan('window.swRouteTabs').size).to eq(1)
    end

    it 'names no active trigger of its own' do
      # The rendered index has no authority here, and a morph that rewrites this
      # class attribute would not re-run Alpine's :class effect -- activeTab
      # never changed -- leaving the highlight stuck on the server's guess.
      stale = render_group(adapter, tabs_app(url: true, active: 1))

      expect(stale).not_to include('sw-tab-trigger sw-tab-active')
      expect(stale).to include(%q{:class="{ 'sw-tab-active': activeTab === 1 }"})
    end
  end

  describe 'in websocket mode' do
    # A canvas page is not an app URL, so there is nowhere to push to and no
    # server seeding path back. Pushed content degrades instead of breaking the
    # page for whoever is reading it.
    let(:adapter) { StreamWeaver::Adapter::AlpineJS.new(url_prefix: '/canvas/test', mode: :websocket) }

    it 'ignores url: and renders plain client tabs' do
      html = nil
      capture_stderr { html = render_group(adapter, tabs_app(url: true, active: 1)) }

      expect(html).to include('x-data="{ activeTab: 1 }"')
      expect(html).to include('type="hidden"')
      expect(html).not_to include('swRouteTabs')
      expect(html).not_to include('@popstate.window')
    end

    it 'warns that url: was ignored' do
      warnings = capture_stderr { render_group(adapter, tabs_app(url: true)) }

      expect(warnings).to match(/StreamWeaver.*url: true.*canvas/)
    end

    it 'warns once per render pass however many groups the page has' do
      groups = [tabs_app(url: true), tabs_app(url: true, key: :panel)]
      warnings = capture_stderr { render_components(adapter, groups) }

      expect(warnings.lines.size).to eq(1)
    end

    it 'warns again on the next render pass' do
      app = tabs_app(url: true)
      capture_stderr { render_group(adapter, app) }
      warnings = capture_stderr { render_group(adapter, app) }

      expect(warnings.lines.size).to eq(1)
    end

    it 'stays quiet for tabs without url:' do
      warnings = capture_stderr { render_group(adapter, tabs_app(url: false)) }

      expect(warnings).to be_empty
    end
  end

  # Locks the exact markup plain tabs produced before route tabs existed. The
  # strings below were generated by rendering these same groups against the
  # commit this change branched from; anything that shifts a byte of them is a
  # regression for every existing tabs user, not a new behavior.
  describe 'tabs without url:' do
    it 'renders eager tabs exactly as before' do
      html = render_group(StreamWeaver::Adapter::AlpineJS.new, tabs_app(active: 1))

      expect(html).to eq([
        %q{<div id="tabs-view" class="sw-tabs sw-tabs-line" x-data="{ activeTab: 1 }">},
        %q{<input type="hidden" name="view" x-model="activeTab">},
        %q{<div class="sw-tabs-list">},
        %q{<button type="button" class="sw-tab-trigger" :class="{ 'sw-tab-active': activeTab === 0 }" },
        %q{@click="activeTab = 0" hx-post="/update" hx-vals="{&quot;view&quot;:0}" hx-swap="none">Alpha</button>},
        %q{<button type="button" class="sw-tab-trigger sw-tab-active" :class="{ 'sw-tab-active': activeTab === 1 }" },
        %q{@click="activeTab = 1" hx-post="/update" hx-vals="{&quot;view&quot;:1}" hx-swap="none">Beta</button>},
        %q{</div>},
        %q{<div class="sw-tab-panel" x-show="activeTab === 0" x-cloak><p>Alpha</p></div>},
        %q{<div class="sw-tab-panel" x-show="activeTab === 1" x-cloak><p>Beta</p></div>},
        %q{</div>}
      ].join)
    end

    it 'renders lazy tabs exactly as before' do
      html = render_group(StreamWeaver::Adapter::AlpineJS.new, tabs_app(lazy: true, active: 1))

      expect(html).to eq([
        %q{<div id="tabs-view" class="sw-tabs sw-tabs-line" x-data="{ activeTab: 1 }">},
        %q{<input type="hidden" name="view" x-model="activeTab">},
        %q{<div class="sw-tabs-list">},
        %q{<button type="button" class="sw-tab-trigger" :class="{ 'sw-tab-active': activeTab === 0 }" },
        %q{@click="activeTab = 0" hx-post="/update" hx-include="[x-model]" hx-vals="{&quot;view&quot;:0}" },
        %q{hx-target="#app-container" hx-swap="morph:innerHTML">Alpha</button>},
        %q{<button type="button" class="sw-tab-trigger sw-tab-active" :class="{ 'sw-tab-active': activeTab === 1 }" },
        %q{@click="activeTab = 1" hx-post="/update" hx-include="[x-model]" hx-vals="{&quot;view&quot;:1}" },
        %q{hx-target="#app-container" hx-swap="morph:innerHTML">Beta</button>},
        %q{</div>},
        %q{<div class="sw-tab-panel" x-show="activeTab === 0" x-cloak><!-- lazy: tab 0 not rendered --></div>},
        %q{<div class="sw-tab-panel" x-show="activeTab === 1" x-cloak><p>Beta</p></div>},
        %q{</div>}
      ].join)
    end

    it 'renders canvas tabs exactly as before' do
      adapter = StreamWeaver::Adapter::AlpineJS.new(url_prefix: '/canvas/test', mode: :websocket)
      html = render_group(adapter, tabs_app(active: 1))

      expect(html).to eq([
        %q{<div id="tabs-view" class="sw-tabs sw-tabs-line" x-data="{ activeTab: 1 }">},
        %q{<input type="hidden" name="view" x-model="activeTab">},
        %q{<div class="sw-tabs-list">},
        %q{<button type="button" class="sw-tab-trigger" :class="{ 'sw-tab-active': activeTab === 0 }" },
        %q{@click="activeTab = 0">Alpha</button>},
        %q{<button type="button" class="sw-tab-trigger sw-tab-active" :class="{ 'sw-tab-active': activeTab === 1 }" },
        %q{@click="activeTab = 1">Beta</button>},
        %q{</div>},
        %q{<div class="sw-tab-panel" x-show="activeTab === 0" x-cloak><p>Alpha</p></div>},
        %q{<div class="sw-tab-panel" x-show="activeTab === 1" x-cloak><p>Beta</p></div>},
        %q{</div>}
      ].join)
    end
  end

  # `warn` writes to $stderr; swapping it keeps spec output pristine and lets
  # the warning be asserted on.
  def capture_stderr
    original = $stderr
    $stderr = StringIO.new
    yield
    $stderr.string
  ensure
    $stderr = original
  end
end
