#!/usr/bin/env ruby
# frozen_string_literal: true

# Add lib to load path for development
$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))

require 'stream_weaver'

StreamWeaver::CLI.run(ARGV)
